name: "angular-sAlert"
description: "simple, smart alerts for AngularJS"
github: https://github.com/aeife/angular-sAlert
version: 1.1.2
download: https://github.com/aeife/angular-sAlert/archive/1.1.2.zip

url: "http://localhost:4000"
baseurl: /angular-sAlert

paginate: 2

markdown: rdiscount
permalink: pretty
highlighter: "pygments"